export const GET_AVIS_LOAD="GET_AVIS_LOAD";
export const GET_AVIS_SUCCESS="GET_AVIS_SUCCESS";
export const GET_AVIS_FAIL="GET_AVIS_FAIL";
export const GET_AVIS="GET_AVIS";
export const POST_AVIS="POST_AVIS";
export const POST_AVIS_FAIL="POST_AVIS_FAIL";
export const DELETE_AVIS_FAIL="DELETE_AVIS_FAIL";